server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: Customer80_Feign
spring:
  application:
    name: microservicecloud-customer-dept
info:
  app.name: provider-dept-service
  company.name: 腾讯科技
  build.artifactId: $project.artifactId$
  build.version: $project.version$
feign:
  hystrix:
    enabled: true #hystrix的服务降级必须配置 在客户端配置，与hystrix熔断不同，熔断是在服务端配置的