server:
  port: 8083
spring:
  application:
    name: microservicecloud-dept #对外暴露的微服务的名字（很重要）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_cloud03?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: a9rg21
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5   #最小维持连接数
      max-wait-millis: 200 #等待连接获取的最大延时时间
      max-total: 5 #最大连接数
      initial-size: 5 #初始化连接数
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*Mapper.xml
logging:
  level:
    com.atguigu.springcloud.dao: trace
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka #设置服务端定义好的注册地址
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-dept-8083 #给微服务起个别名
    prefer-ip-address: true #鼠标放在别名上时左下角显示ip地址

#导jar 配置父工程（resources插件）info读取的路径，以及信息读取的规则 最后yml定义info
#info下面的内容随意定义，按json格式就好
info:
  app.name: provider-dept-service
  company.name: 腾讯科技
  build.artifactId: $project.artifactId$
  build.version: $project.version$