server:
  port: 7001
eureka:
  instance:
#    hostname: localhost（单机版写法） #eureka服务端的实例名称--其他注册进来的微服务可以在自己yml里改
    hostname: eureka7001.com
  client:
    register-with-eureka: false #表明不向eureka注册中心注册自己
    fetch-registry: false   #表明自身端口是服务端，不需要去检索
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置访问eureka的服务地址
       defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  server:
#    enable-self-preservation: false 关闭eureka自我保护机制，没有特殊情况不会关闭
#springcloud多维度的组件技术添加套路--导jar-配yml-主启动类添加注解启动enable开头
